# This is the basic pipeline
language: shell
sudo: false
addons:
  apt:
    packages:
    # required packages according to bitbake docu
    - build-essential
    - chrpath
    - diffstat
    - gawk
    - gcc-multilib
    - git-core
    - libsdl1.2-dev
    - python3
    - socat
    - texinfo
    - unzip
    - wget
    - xterm
env:
    global:
      - SCA_ENABLE=1
      # distro to build
      - DISTRO=scatest
      # Target branch of other layer-repos
      - SCA_BRANCH=thud
      # bitbake target to build
      - SCA_TARGET_IMG=core-image-minimal-scatest
      # Builddir
      - SCA_BUILDDIR=${TRAVIS_BUILD_DIR}/build
jobs:
  include:
  - name: "qemux86 standard options"
    env: MACHINE=qemux86
  - name: "qemux86 + meta-oe"
    env: MACHINE=qemux86 _WITH_METAOE=1
  - name: "qemux86 + clang"
    env: MACHINE=qemux86 _WITH_METACLANG=1
  - name: "qemux86 + clang + meta-oe"
    env: MACHINE=qemux86 _WITH_METACLANG=1 _WITH_METAOE=1
script:
    # Clone needed repos
    - git clone git://git.yoctoproject.org/poky.git/ -b ${SCA_BRANCH} ${TRAVIS_BUILD_DIR}/poky
    - if [ ! -z ${_WITH_METAOE} ]; then git clone git://git.openembedded.org/meta-openembedded -b ${SCA_BRANCH} ${TRAVIS_BUILD_DIR}/meta-oe; fi
    - if [ ! -z ${_WITH_METACLANG} ]; then git clone https://github.com/kraj/meta-clang.git -b ${SCA_BRANCH} ${TRAVIS_BUILD_DIR}/meta-clang; fi
    # setup poky (is needed to run bitbake-layers afterwards)
    - source ${TRAVIS_BUILD_DIR}/poky/oe-init-build-env
    # Add meta-sca layer
    - bitbake-layers add-layer ${TRAVIS_BUILD_DIR}
    - if [ ! -z ${_WITH_METACLANG} ]; then bitbake-layers add-layer ${TRAVIS_BUILD_DIR}/meta-clang; fi
    - if [ ! -z ${_WITH_METAOE} ]; then bitbake-layers add-layer ${TRAVIS_BUILD_DIR}/meta-oe/meta-oe; fi
    # Only run bitbake-parse without actually building anything
    # this is needed as travis-ci is slow as hell and has 
    # multiple limitations regarding buildtime, which
    # prevents using it as the main CI for bitbake
    - bitbake -p ${SCA_TARGET_IMG}
